// <auto-generated />
using System;
using Internal.MeetingWasteKiller.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Internal.MeetingWasteKiller.SqlServer.Migrations
{
    [DbContext(typeof(MeetingWasteKillerDbContext))]
    partial class MeetingWasteKillerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Internal.MeetingWasteKiller.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("Attachments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            BlobUrl = "https://fakestorage.blob.core.windows.net/attachments/agenda-sprint.pdf",
                            FileName = "agenda-sprint.pdf",
                            MeetingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000001"),
                            BlobUrl = "https://fakestorage.blob.core.windows.net/attachments/arch-diagram.pdf",
                            FileName = "arch-diagram.pdf",
                            MeetingId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000002"),
                            BlobUrl = "https://fakestorage.blob.core.windows.net/attachments/notes.docx",
                            FileName = "notes.docx",
                            MeetingId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("e0000001-0000-0000-0000-000000000001"),
                            BlobUrl = "https://fakestorage.blob.core.windows.net/attachments/bug-report.pdf",
                            FileName = "bug-report.pdf",
                            MeetingId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("f0000001-0000-0000-0000-000000000001"),
                            BlobUrl = "https://fakestorage.blob.core.windows.net/attachments/q3-agenda.pdf",
                            FileName = "q3-agenda.pdf",
                            MeetingId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        });
                });

            modelBuilder.Entity("Internal.MeetingWasteKiller.Domain.Entities.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsAlert")
                        .HasColumnType("bit");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WasteReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WasteScore")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Date = new DateTime(2026, 5, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 90,
                            IsAlert = true,
                            Summary = "Sprint planning per il Q2. Definizione backlog e stime.",
                            Title = "Sprint Planning",
                            WasteReason = "Troppi partecipanti, durata eccessiva rispetto al valore prodotto.",
                            WasteScore = 80m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Date = new DateTime(2026, 6, 1, 9, 30, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 30,
                            IsAlert = false,
                            Summary = "Sincronizzazione quotidiana del team di sviluppo.",
                            Title = "Daily Standup",
                            WasteReason = "Meeting efficiente, breve e focalizzato.",
                            WasteScore = 15m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Date = new DateTime(2026, 5, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 120,
                            IsAlert = true,
                            Summary = "Revisione dell'architettura del sistema di autenticazione.",
                            Title = "Architecture Review",
                            WasteReason = "Discussioni circolari senza decisioni concrete.",
                            WasteScore = 65m
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Date = new DateTime(2026, 6, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 60,
                            IsAlert = false,
                            Summary = "Retrospettiva di fine sprint: punti positivi e aree di miglioramento.",
                            Title = "Team Retrospective",
                            WasteReason = "Meeting produttivo con azioni concrete identificate.",
                            WasteScore = 30m
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Date = new DateTime(2026, 6, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 180,
                            IsAlert = true,
                            Summary = "Analisi critica del bug in produzione su modulo pagamenti.",
                            Title = "Emergency Bug Meeting",
                            WasteReason = "Meeting non strutturato, tre ore per decidere un rollback.",
                            WasteScore = 90m
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Date = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 120,
                            IsAlert = true,
                            Summary = "Pianificazione obiettivi e roadmap per il terzo trimestre.",
                            Title = "Q3 Planning",
                            WasteReason = "Agenda poco chiara, rischio di derive fuori tema.",
                            WasteScore = 75m
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000001"),
                            Date = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 45,
                            IsAlert = false,
                            Summary = "Allineamento settimanale sui task in corso e blocchi.",
                            Title = "Team Sync",
                            WasteReason = "Sync rapido ed efficace.",
                            WasteScore = 20m
                        });
                });

            modelBuilder.Entity("Internal.MeetingWasteKiller.Domain.Entities.MeetingParticipant", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MeetingId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MeetingParticipants");

                    b.HasData(
                        new
                        {
                            MeetingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            MeetingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            MeetingId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            MeetingId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            MeetingId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            MeetingId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            MeetingId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            MeetingId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            MeetingId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            MeetingId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            MeetingId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            MeetingId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            MeetingId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            MeetingId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            MeetingId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            MeetingId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            MeetingId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            MeetingId = new Guid("00000001-0000-0000-0000-000000000001"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            MeetingId = new Guid("00000001-0000-0000-0000-000000000001"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Internal.MeetingWasteKiller.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DailyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DailyCost = 800m,
                            Email = "martina@company.com",
                            Name = "Mario Rossi",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DailyCost = 600m,
                            Email = "dev@company.com",
                            Name = "Luca Bianchi",
                            Role = "Senior Dev"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DailyCost = 350m,
                            Email = "junior@company.com",
                            Name = "Sara Verdi",
                            Role = "Junior Dev"
                        });
                });

            modelBuilder.Entity("Internal.MeetingWasteKiller.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Internal.MeetingWasteKiller.Domain.Entities.Meeting", "Meeting")
                        .WithMany("Attachments")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Internal.MeetingWasteKiller.Domain.Entities.MeetingParticipant", b =>
                {
                    b.HasOne("Internal.MeetingWasteKiller.Domain.Entities.Meeting", "Meeting")
                        .WithMany("Participants")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internal.MeetingWasteKiller.Domain.Entities.User", "User")
                        .WithMany("MeetingParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Internal.MeetingWasteKiller.Domain.Entities.Meeting", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Internal.MeetingWasteKiller.Domain.Entities.User", b =>
                {
                    b.Navigation("MeetingParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
